services:
  api:
    build: .
    command: node --watch index.js
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:dev@db:5432/tasks
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure # <-- If the bd takes more than a second, the API tries against instead of being killed
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: tasks
    volumes:
      - taskdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tasks"]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  taskdata:

networks:
  app-network:
    driver: bridge